version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
